# Generated by Django 4.2.7 on 2023-11-10 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('active_investment', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_withdrawal', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Total_earnings', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('last_withdraw', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referral_bonus', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
