# Generated by Django 4.2.7 on 2023-11-07 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_alter_profile_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_id', models.CharField(max_length=50, unique=True)),
                ('plan', models.CharField(blank=True, choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('estate', 'Real Estate'), ('pro', 'Trading Pro')], max_length=12, null=True)),
                ('channel', models.CharField(blank=True, choices=[('BTC', 'BTC'), ('THETHER USDT', 'THETHER USDT'), ('BNB', 'BNB'), ('ETH', 'ETH')], default='BTC', max_length=15, null=True)),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('invest', 'invest'), ('withdraw', 'withdraw')], default='deposit', max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approve', 'approved'), ('decline', 'declined')], default='pending', max_length=10)),
                ('progress', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed')], default='pending', editable=False, max_length=12)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
