# Generated by Django 4.2.7 on 2023-12-26 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transact_id', models.CharField(max_length=50, unique=True)),
                ('plan', models.CharField(blank=True, choices=[('standard', 'Standard'), ('silver', 'Silver'), ('premium', 'Premium'), ('ultra', 'Ultra')], max_length=12, null=True)),
                ('channel', models.CharField(blank=True, choices=[('BTC', 'BTC'), ('TETHER USDT', 'TETHER USDT'), ('BNB', 'BNB'), ('ETHEREUM', 'ETHEREUM')], default='BTC', max_length=15, null=True)),
                ('type', models.CharField(choices=[('deposit', 'deposit'), ('invest', 'invest'), ('withdraw', 'withdraw'), ('referral', 'referral'), ('bonus', 'bonus'), ('received', 'received')], default='deposit', max_length=9)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approve'), ('declined', 'decline')], default='pending', max_length=10)),
                ('progress', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('completed', 'completed')], default='pending', editable=False, max_length=12)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.profile')),
            ],
        ),
    ]
