# Generated by Django 4.2.7 on 2023-12-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='plan',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('silver', 'Silver'), ('premium', 'Premium'), ('ultra', 'Ultra'), ('promo', 'Promo'), ('visa', 'Visa')], max_length=12, null=True),
        ),
    ]
