# Generated by Django 4.2.7 on 2024-01-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.CharField(blank=True, default='BTC', max_length=15, null=True),
        ),
    ]
