# Generated by Django 4.2.7 on 2023-11-06 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=17)),
                ('country', models.CharField(max_length=40)),
                ('verified', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('key', models.CharField(blank=True, max_length=70, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
