# Generated by Django 4.2.7 on 2023-11-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_referred_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country_code',
            field=models.CharField(max_length=5),
        ),
    ]
