# Generated by Django 4.2.7 on 2024-01-01 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_setup_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
