# Generated by Django 4.2.7 on 2024-01-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_remove_setup_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='usd',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
