# Generated by Django 4.2.7 on 2024-01-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_setup_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='withdraw_charges',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
